[package]
name = "sothis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.0"
env = "0.0.0"
reqwest = "0.11.18"
serde = "1.0.163"
tokio = { version = "1.28.1", features = ["full"] }
